name: Main

on:
  pull_request:
  push:
    branches: main
    tags:
      - "v*"

jobs:
  test:
    name: Test Suite
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@main
      - uses: bahmutov/npm-install@v1
      - run: yarn test

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@main
      - uses: bahmutov/npm-install@v1
      - run: yarn compile
      - run: npx vsce package -o extension.vsix
      - uses: actions/upload-artifact@v3
        with:
          name: vsix
          path: extension.vsix

  release:
    name: Release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    steps:
      - uses: actions/checkout@main
      # Make sure we don't forget to change version in package.json
      - uses: geritol/match-tag-to-package-version@0.2.0
        with:
          TAG_PREFIX: v
      - uses: actions/download-artifact@v3
        with:
          name: vsix
      # Release on Visual Studio Marketplace
      - run: npx vsce publish --packagePath extension.vsix -p ${{ secrets.VSCE_TOKEN }}
      # Release on Open VSX
      - run: npx ovsx publish --packagePath extension.vsix -p ${{ secrets.OVSX_TOKEN }}
      # Create a release on Github
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "extension.vsix"
          body: See [CHANGELOG](https://github.com/mathiassoeholm/markdown-link-updater/blob/main/CHANGELOG.md) for details.
          token: ${{ secrets.GITHUB_TOKEN }}
